In [1]:
# Import basic libraries
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import gzip

In [2]:
test_df = pd.DataFrame(pd.read_csv('../00_Resources/fake_or_real_news.csv'))
test_df = test_df.drop(columns=['Unnamed: 0'])
test_df = test_df.replace({'FAKE': 'False', 'REAL': 'True'})
test_df

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",False
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,False
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,True
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",False
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,True
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,True
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,False
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,False
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",True
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,True

In [3]:
with open('../00_Resources/true_fake.csv', 'rb') as fd:
    gzip_fd = gzip.GzipFile(fileobj=fd)
    df = pd.read_csv(gzip_fd)
df = df.drop(columns={'Unnamed: 0','subject','date'})
df = df.rename(columns={'category':'label'})
# df = df.append(test_df, ignore_index=True)
df = df.sample(frac=1).reset_index(drop=True)
# df = df.loc[df['label'] != 'unknown']
df

,title,text,label
0,General Motors NAILS Trump For Lying After He...,Donald Trump just attacked an American car com...,False
1,Advocate For Legal Rape Says Trump’s Victory ...,Daryush Valizadeh is a sexist and misogynist w...,False
2,ISLAMIC TERRORIST ORGANIZATION Joins Obama And...,"What does Obama, the Democrat Party, the state...",False
3,THE TRUTH ABOUT Why SORE LOSER Obama Is Using ...,Make no mistake: it s payback time. In orderin...,False
4,Federal judge being considered for US Supreme ...,"WASHINGTON (Reuters) - Ketanji Brown Jackson, ...",True
...,...,...,...
44893,"Trump: Hurricane Irma has ""absolutely historic...",WASHINGTON (Reuters) - U.S. President Donald T...,True
44894,BOMBSHELL: Trump Is Being Investigated By SIX...,You can probably expect Donald Trump to contin...,False
44895,RNC Blasts White Supremacist’s Tweet On Big S...,It happened again. One would assume that after...,False
44896,Key House lawmaker: Dodd-Frank overhaul remain...,WASHINGTON (Reuters) - The Republican chairman...,True
44897,"Ex-U.S. Attorney Bharara, fired by Trump, join...",NEW YORK (Reuters) - Former Manhattan U.S. Att...,True

In [4]:
df_url = pd.DataFrame(pd.read_csv('../00_Resources/fake_news_with_url.csv'))
df_url = df_url.rename(columns={'Headline':'title','Body':'text'})
df_url['label'] = df_url['Label'].replace({0: 'False', 1: 'True'})
df_url = df_url.drop(columns=['URLs','Label'])
df_url = df_url.dropna(how='any')
df_url

,title,text,label
0,Four ways Bob Corker skewered Donald Trump,Image copyright Getty Images\nOn Sunday mornin...,True
1,Linklater's war veteran comedy speaks to moder...,"LONDON (Reuters) - “Last Flag Flying”, a comed...",True
2,Trump’s Fight With Corker Jeopardizes His Legi...,The feud broke into public view last week when...,True
3,Egypt's Cheiron wins tie-up with Pemex for Mex...,MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...,True
4,Jason Aldean opens 'SNL' with Vegas tribute,"Country singer Jason Aldean, who was performin...",True
...,...,...,...
4003,CNN and Globalist Exposed - Steve Quayle and A...,"Vietnam Is in Great Danger, You Must Publish a...",False
4004,Trends to Watch,Trends to Watch\n% of readers think this story...,False
4005,Trump Jr. Is Soon To Give A 30-Minute Speech F...,Trump Jr. Is Soon To Give A 30-Minute Speech F...,False
4007,China to accept overseas trial data in bid to ...,SHANGHAI (Reuters) - China said it plans to ac...,True
4008,Vice President Mike Pence Leaves NFL Game Beca...,Vice President Mike Pence Leaves NFL Game Beca...,False

In [7]:
df1 = pd.DataFrame(pd.read_csv('../00_Resources/Fake-News/train.csv'))
df2 = pd.DataFrame(pd.read_csv('../00_Resources/Fake-News/test.csv'))
df3 = pd.DataFrame(pd.read_csv('../00_Resources/Fake-News/submit.csv'))

df4 = df1.append(df2, ignore_index=True)
df_merge = pd.merge(df3, df4, on='id')

df_merge['label'] = df_merge['label_x'].replace({1: 'False', 0: 'True'})
df_merge = df_merge.drop(columns=['id','label_x','author','label_y'])
df_merge = df_merge.dropna(how='any')

df_merge

,title,text,label
0,"Specter of Trump Loosens Tongues, if Not Purse...","PALO ALTO, Calif. — After years of scorning...",True
1,Russian warships ready to strike terrorists ne...,Russian warships ready to strike terrorists ne...,False
2,#NoDAPL: Native American Leaders Vow to Stay A...,Videos #NoDAPL: Native American Leaders Vow to...,True
3,"Tim Tebow Will Attempt Another Comeback, This ...","If at first you don’t succeed, try a different...",False
4,Keiser Report: Meme Wars (E995),42 mins ago 1 Views 0 Comments 0 Likes 'For th...,False
...,...,...,...
5195,The Bangladeshi Traffic Jam That Never Ends - ...,Of all the dysfunctions that plague the world’...,True
5196,John Kasich Signs One Abortion Bill in Ohio bu...,WASHINGTON — Gov. John Kasich of Ohio on Tu...,False
5197,"California Today: What, Exactly, Is in Your Su...",Good morning. (Want to get California Today by...,True
5198,300 US Marines To Be Deployed To Russian Borde...,« Previous - Next » 300 US Marines To Be Deplo...,False
5199,"Awkward Sex, Onscreen and Off - The New York T...",Perhaps you’ve seen the new TV series whose pi...,True

In [8]:
df2 = df.append(test_df, ignore_index=True)
df3 = df2.append(df_url, ignore_index=True)
df4 = df3.append(df_merge, ignore_index=True)

df5 = df4.sample(frac=1).reset_index(drop=True)

df5

,title,text,label
0,"EU urges Spain to talk to Catalans, condemns v...",BRUSSELS (Reuters) - The EU executive urged Sp...,True
1,Project Veritas Releases Fourth Video Exposing...,"Posted on October 28, 2016 by Jack Burns \nAs ...",True
2,FORMER U.S. ATTORNEY: “It’s VERY Clear Intel C...,JOE DIGENOVA has been around D.C for decades a...,False
3,OBAMA Stammers Like Crazy Trying To Slam Trump...,Wow! Talk about a psych out! Obama stutters an...,False
4,"Connecticut attorney general, others ask Equif...",WASHINGTON (Reuters) - Connecticut’s attorney ...,True
...,...,...,...
60287,"10/5 TRS-PNC Park: Bucs Win in '71, '79; Lose ...",Red Flag Warning: These California Wildfires A...,False
60288,CROOKED HILLARY GETS LUCKY: Obama’s State Dept...,BIRDS OF A FEATHER FLOCK TOGETHER-Dirty politi...,False
60289,France pushes U.N. to impose sanctions over Li...,UNITED NATIONS (Reuters) - France said on Tues...,True
60290,Russian economy minister : U.S. sanctions to h...,MOSCOW (Reuters) - Draft new U.S. sanctions ag...,True
60291,HAARP to 'make the sky glow' with radio waves ...,"For four nights beginning on Thursday night, a...",False

In [ ]:
df5.to_csv('../00_Resources/all_merged_datasets.csv', compression='gzip')